# Catppuccin Mocha

[colors]
background = #1e1e2e
foreground = #cdd6f4
dim_foreground = #a6adc8

[urgent_low]
bar = #6c7086
accent = #6c7086

[urgent_normal]
bar = #89b4fa
accent = #89b4fa

[urgent_warning]
bar = #f9e2af
accent = #f9e2af

[urgent_error]
bar = #f38ba8
accent = #f38ba8

[urgent_critical]
bar = #f38ba8
accent = #f38ba8