# Dracula

[colors]
background = #282a36
foreground = #f8f8f2
dim_foreground = #6272a4

[urgent_low]
bar = #6272a4
accent = #6272a4

[urgent_normal]
bar = #bd93f9
accent = #bd93f9

[urgent_warning]
bar = #f1fa8c
accent = #f1fa8c

[urgent_error]
bar = #ff5555
accent = #ff5555

[urgent_critical]
bar = #ff5555
accent = #ff79c6