[general]
radius = 6
bar_style = edge
background_opacity = 1

[colors]
background = #f5f5f5
title_text = #333333
body_text = #888888
bar_background = #f5f5f5

[urgent_low]
bar = #5b5b5b
outline = #b0b0b0

[urgent_normal]
bar = #3d5566
outline = #7eb8da

[urgent_warning]
bar = #8a6d1a
outline = #e8c170

[urgent_error]
bar = #93332b
outline = #e88a8a

[urgent_critical]
bar = #fb4934
outline = #d66060
