[general]
radius = 12
blur_enabled = true
blur_radius = 24
background_opacity = 0.50

[colors]
background = #26262b
foreground = #e6e6ea
dim_foreground = #a8a8b0

[urgent_low]
bar = #6c7086
accent = #6c7086

[urgent_normal]
bar = #89b4fa
accent = #89b4fa

[urgent_warning]
bar = #f9e2af
accent = #f9e2af

[urgent_error]
bar = #f38ba8
accent = #f38ba8

[urgent_critical]
bar = #f38ba8
accent = #fb4934
