# Gruvbox Dark

[colors]
background = #282828
foreground = #ebdbb2
dim_foreground = #a89984

[urgent_low]
bar = #928374
accent = #928374

[urgent_normal]
bar = #83a598
accent = #83a598

[urgent_warning]
bar = #fabd2f
accent = #fabd2f

[urgent_error]
bar = #fb4934
accent = #fb4934

[urgent_critical]
bar = #fb4934
accent = #cc241d