[general]
radius = 4
blur_enabled = false
bar_style = edge
background_opacity = 0.75

[colors]
background = #2a2a2a
foreground = #ffffff
dim_foreground = #999999

[urgent_low]
bar = #666666
accent = #666666

[urgent_normal]
bar = #888888
accent = #888888

[urgent_warning]
bar = #aaaaaa
accent = #aaaaaa

[urgent_error]
bar = #cccccc
accent = #cccccc

[urgent_critical]
bar = #eeeeee
accent = #eeeeee
