[general]
radius = 4
bar_style = edge
background_opacity = 0.75

[colors]
background = #2a2a2a
title_text = #ffffff
body_text = #999999

[urgent_low]
bar = #666666
outline = #666666

[urgent_normal]
bar = #888888
outline = #888888

[urgent_warning]
bar = #aaaaaa
outline = #aaaaaa

[urgent_error]
bar = #cccccc
outline = #cccccc

[urgent_critical]
bar = #eeeeee
outline = #eeeeee
