# Nord

[colors]
background = #2e3440
foreground = #d8dee9
dim_foreground = #4c566a

[urgent_low]
bar = #4c566a
accent = #4c566a

[urgent_normal]
bar = #88c0d0
accent = #88c0d0

[urgent_warning]
bar = #ebcb8b
accent = #ebcb8b

[urgent_error]
bar = #bf616a
accent = #bf616a

[urgent_critical]
bar = #bf616a
accent = #d08770