# Solarized Dark

[colors]
background = #002b36
foreground = #839496
dim_foreground = #657b83

[urgent_low]
bar = #586e75
accent = #586e75

[urgent_normal]
bar = #268bd2
accent = #268bd2

[urgent_warning]
bar = #b58900
accent = #b58900

[urgent_error]
bar = #dc322f
accent = #dc322f

[urgent_critical]
bar = #cb4b16
accent = #dc322f